@extends('layouts.app') @section('title','Transaction') @section('topbar','Transaction') @section('content')
<div class="mobile-shell"><div class="page-head"><div><h2>{{ $transaction->type->label() }}</h2><p class="mono">{{ $transaction->reference }}</p></div><span class="badge {{ $transaction->status->value==='completed'?'green':($transaction->status->value==='rejected'?'red':'orange') }}">{{ str($transaction->status->value)->replace('_',' ')->upper() }}</span></div>
@if($transaction->review_reason)<div class="alert warning">{{ $transaction->review_reason }}</div>@endif @if($transaction->rejection_reason)<div class="alert error"><b>Transaction rejected:</b> {{ $transaction->rejection_reason }}</div>@endif
@if($transaction->agent)<div class="card" style="margin-bottom:14px"><div style="display:flex;justify-content:space-between;gap:12px"><div><span class="tiny muted">AI IDENTIFIED AGENT</span><h3 style="margin:4px 0">{{ $transaction->agent->agent_id }} · {{ $transaction->agent->username }}</h3><div class="small muted">{{ $transaction->brand->name }} · Brand derived automatically from agent master data</div></div>@if(($currentOutstanding??0)>0)<span class="badge orange">IN CREDIT {{ number_format($currentOutstanding,2) }} ETB</span>@endif</div></div>@endif
@if($transaction->type->requiresAgentScreenshot())<section class="card" style="margin-bottom:14px"><h3 class="section-title">1. Agent-system screenshot</h3>@php($agentEvidence=$transaction->evidenceFiles->where('kind',App\Enums\EvidenceKind::AgentSystem)->sortByDesc('id')->first())@if(!$agentEvidence || in_array($agentEvidence->status->value,['needs_reupload','failed']))<form method="post" action="{{ route('employee.transactions.agent-evidence',$transaction) }}" enctype="multipart/form-data" class="stack">@csrf<div class="upload"><b>Upload one agent-system screenshot</b><p class="tiny muted">AI reads Agent ID, username, amount, date/time and identifies the brand. Blurry evidence is rejected.</p><input type="file" name="screenshot" accept="image/*" required></div><button class="btn btn-primary">Upload & read automatically</button></form>@else<div class="status-line"><span>Screenshot</span><span class="badge">{{ $agentEvidence->status->value }}</span></div>@if($agentEvidence->extracted)<div class="grid grid-2" style="margin-top:10px">@foreach(['agent_id'=>'Agent ID','agent_username'=>'Username','amount'=>'Amount','transaction_at'=>'Date / time','brand_hint'=>'Brand hint'] as $key=>$label)<div class="lock-field"><span class="tiny muted">{{ strtoupper($label) }} 🔒</span><b>{{ data_get($agentEvidence->extracted,$key,'—') }}</b></div>@endforeach</div>@endif<div style="margin-top:10px"><a class="btn btn-sm btn-outline" href="{{ route('evidence.show',$agentEvidence) }}">View screenshot</a></div>@endif</section>@endif
@if($transaction->type->requiresBankEvidence() && $transaction->agent_id)<section class="card" style="margin-bottom:14px"><h3 class="section-title">2. Bank payment screenshot(s)</h3><p class="small muted">Upload one or multiple bank receipts. Each is verified separately, then combined. Global duplicate TX IDs are hard blocked.</p><form method="post" action="{{ route('employee.transactions.bank-evidence',$transaction) }}" enctype="multipart/form-data" class="stack">@csrf<div class="upload"><input type="file" name="screenshots[]" multiple accept="image/*" required><p class="tiny muted">You can attach 1–12 screenshots from different banks.</p></div><button class="btn btn-primary">Add payment screenshot(s)</button></form>@foreach($transaction->payments as $p)<div class="evidence" style="margin-top:10px"><div style="display:flex;justify-content:space-between"><b>{{ $p->fromBank?->name ?? $p->from_bank_raw }} → {{ $p->toBank?->name ?? $p->to_bank_raw }}</b><span class="badge {{ $p->internal_status->value==='valid'?'green':($p->internal_status->value==='rejected'?'red':'orange') }}">{{ $p->internal_status->value }}</span></div><div class="grid grid-2" style="margin-top:9px"><div class="lock-field"><span class="tiny muted">AMOUNT 🔒</span><b>{{ number_format((float)$p->amount,2) }} ETB</b></div><div class="lock-field"><span class="tiny muted">TX ID 🔒</span><b class="mono">{{ $p->transaction_id_raw }}</b></div><div class="lock-field"><span class="tiny muted">FROM 🔒</span><b>{{ $p->sender_name }} · {{ $p->sender_account }}</b></div><div class="lock-field"><span class="tiny muted">TO 🔒</span><b>{{ $p->receiver_name }} · {{ $p->receiver_account }}</b></div></div>@if($p->time_difference_minutes!==null && $p->time_difference_minutes>60)<div class="alert {{ $p->risk_level?->value==='critical'?'error':'warning' }}" style="margin:10px 0 0">Payment-to-top-up difference: <b>{{ $p->time_difference_minutes }} minutes</b> · {{ strtoupper($p->risk_level?->value??'') }}</div>@endif</div>@endforeach</section>@endif
@if($transaction->type===App\Enums\TransactionType::Withdrawal && $transaction->agent_id)<section class="card" style="margin-bottom:14px"><h3 class="section-title">Reason for balance removal</h3><form method="post" action="{{ route('employee.transactions.reason',$transaction) }}" class="stack">@csrf<textarea class="textarea" name="reason" required placeholder="Why is this balance being removed?">{{ $transaction->reason }}</textarea><button class="btn">Save reason</button></form></section>@endif
@php($allowedCorrections=auth()->user()->permissions?->correction_fields??[])
@if(count($allowedCorrections) && !in_array($transaction->status->value,['completed','rejected','cancelled']))
<section class="card" style="margin-bottom:14px"><h3 class="section-title">Request AI correction</h3><p class="small muted">You cannot edit extracted values. If AI read a permitted field incorrectly, request a correction for Admin approval.</p>
@if($agentEvidence && $agentEvidence->extracted)
@php($agentFields=array_values(array_intersect($allowedCorrections,['agent_id','agent_username','agent_amount','agent_transaction_date','brand_hint'])))
@if(count($agentFields))<details class="evidence"><summary style="cursor:pointer"><b>Agent-system extraction</b></summary><form method="post" action="{{ route('employee.transactions.corrections',$transaction) }}" class="stack" style="margin-top:10px">@csrf<input type="hidden" name="evidence_file_id" value="{{ $agentEvidence->id }}"><select class="select" name="field" required>@foreach($agentFields as $f)<option value="{{ $f }}">{{ str($f)->replace('_',' ')->title() }}</option>@endforeach</select><input class="input" name="proposed_value" placeholder="Correct value visible in screenshot" required><textarea class="textarea" name="reason" placeholder="Why did AI read it incorrectly?" required></textarea><button class="btn">Send to Admin</button></form></details>@endif
@endif
@foreach($transaction->payments as $p)
@php($paymentFields=array_values(array_intersect($allowedCorrections,['amount','sender_bank','sender_account','sender_name','transaction_id','transaction_date'])))
@if(count($paymentFields))<details class="evidence" style="margin-top:8px"><summary style="cursor:pointer"><b>Bank payment {{ $loop->iteration }}</b> · {{ $p->transaction_id_raw }}</summary><form method="post" action="{{ route('employee.transactions.corrections',$transaction) }}" class="stack" style="margin-top:10px">@csrf<input type="hidden" name="payment_record_id" value="{{ $p->id }}"><input type="hidden" name="evidence_file_id" value="{{ $p->evidence_file_id }}"><select class="select" name="field" required>@foreach($paymentFields as $f)<option value="{{ $f }}">{{ str($f)->replace('_',' ')->title() }}</option>@endforeach</select><input class="input" name="proposed_value" placeholder="Correct value visible in screenshot" required><textarea class="textarea" name="reason" placeholder="Why did AI read it incorrectly?" required></textarea><button class="btn">Send to Admin</button></form></details>@endif
@endforeach
<div class="tiny muted" style="margin-top:10px">Receiver bank, receiver account and receiver name are intentionally never correction-enabled.</div></section>
@endif
<section class="card" style="margin-bottom:14px"><h3 class="section-title">Validation</h3><div class="status-line"><span>Agent / brand</span><b>{{ $transaction->agent_id?'Verified':'Pending' }}</b></div>@if($transaction->type->requiresBankEvidence())<div class="status-line"><span>Valid payment total</span><b>{{ number_format((float)$transaction->valid_payment_total,2) }} ETB</b></div><div class="status-line"><span>Agent-system amount</span><b>{{ $transaction->amount!==null?number_format((float)$transaction->amount,2).' ETB':'Pending' }}</b></div><div class="status-line"><span>External verification</span><b>{{ $transaction->external_verification_status?->value ?? 'pending' }}</b></div>@endif<div class="status-line"><span>Risk</span><b>{{ $transaction->risk_level?->value ?? 'pending' }}</b></div>@if(($currentOutstanding??0)>0 && $transaction->type!==App\Enums\TransactionType::CreditRepayment)<div class="alert warning" style="margin-top:12px"><b>Agent is already in credit.</b> You may continue. This warning is recorded in the transaction context.</div>@endif</section>
@if($transaction->status===App\Enums\TransactionStatus::ReadyForReview)<section class="card"><h3 class="section-title">Final confirmation</h3><form method="post" action="{{ route('employee.transactions.finalize',$transaction) }}" class="stack">@csrf @if($transaction->risk_level===App\Enums\RiskLevel::Critical)<div class="alert error"><b>Critical time difference.</b> Two confirmations and your password are required.</div><label class="check"><input type="checkbox" name="critical_confirmation_1" value="1" required> I checked the payment details and intentionally use this older payment.</label><label class="check"><input type="checkbox" name="critical_confirmation_2" value="1" required> I understand this exceeds the critical time threshold.</label><input class="input" type="password" name="password" placeholder="Confirm your password" required>@endif<button class="btn btn-success">Complete transaction</button></form></section>@endif
@if(!in_array($transaction->status->value,['completed','rejected','cancelled']))<form method="post" action="{{ route('employee.transactions.cancel',$transaction) }}" style="margin-top:14px">@csrf<button class="btn btn-outline">Cancel draft</button></form>@endif</div>
@endsection
