@extends('layouts.app')
@section('title','Profile') @section('topbar','Profile & Security')
@section('content')
<div class="page-head"><div><h2>{{ $user->name }}</h2><p>{{ $user->username }} · {{ ucfirst($user->role->value) }}</p></div></div>
<div class="grid grid-2">
<section class="card"><h3 class="section-title">Change password</h3><p class="small muted">Changing your password signs out other remembered devices while keeping this device signed in with a newly rotated token.</p><form method="post" action="{{ route('profile.password') }}" class="stack">@csrf @method('PUT')<div class="field"><label>Current password</label><input class="input" type="password" name="current_password" autocomplete="current-password" required></div><div class="field"><label>New password</label><input class="input" type="password" name="password" autocomplete="new-password" minlength="12" required></div><div class="field"><label>Confirm new password</label><input class="input" type="password" name="password_confirmation" autocomplete="new-password" minlength="12" required></div><button class="btn btn-primary">Change password</button></form></section>
<section class="card"><h3 class="section-title">Remembered devices</h3><p class="small muted">Persistent login remains active until logout, Admin revocation, password rotation or long-expiry.</p><div class="table-wrap"><table class="table"><thead><tr><th>Device</th><th>Last seen</th><th>Status</th></tr></thead><tbody>@forelse($devices as $d)<tr><td><b>{{ $d->device_label ?: 'Unknown device' }}</b><div class="tiny muted">{{ $d->ip_address }}</div></td><td>{{ optional($d->last_seen_at)->format('Y-m-d H:i') ?? '—' }}</td><td><span class="badge {{ $d->isUsable()?'green':'red' }}">{{ $d->isUsable()?'active':'revoked/expired' }}</span></td></tr>@empty<tr><td colspan="3" class="empty">No remembered devices.</td></tr>@endforelse</tbody></table></div>@if($user->isAdmin())<p class="tiny muted" style="margin-top:12px">Admins can revoke individual sessions from Device Sessions.</p>@endif</section>
</div>
@endsection
