<?php

return [
    'device_cookie' => [
        'name' => env('DEVICE_COOKIE_NAME', 'agent_audit_device'),
        'years' => (int) env('DEVICE_COOKIE_YEARS', 25),
        'secure' => (bool) env('DEVICE_COOKIE_SECURE', false),
    ],
    'imports' => ['max_agent_rows' => (int) env('MAX_AGENT_IMPORT_ROWS', 50000)],
    'evidence' => [
        'disk' => env('EVIDENCE_DISK', env('FILESYSTEM_DISK', 'private')),
        'max_kb' => 12288,
        'allowed_mimes' => ['image/jpeg', 'image/png', 'image/webp'],
        'max_bank_screenshots_per_transaction' => 12,
    ],
    'hard_non_correctable_fields' => [
        'receiver_bank',
        'receiver_account',
        'receiver_name',
    ],
    'withdrawal_reasons' => [
        'wrong_previous_topup' => 'Wrong previous top-up',
        'agent_requested_return' => 'Agent requested balance return',
        'account_closure' => 'Account closure',
        'correction' => 'Correction',
        'fraud_suspicious' => 'Fraud / suspicious activity',
        'other' => 'Other',
    ],
    'correction_fields' => [
        'amount',
        'sender_bank',
        'sender_account',
        'sender_name',
        'transaction_id',
        'transaction_date',
        'agent_id',
        'agent_username',
        'agent_amount',
        'agent_transaction_date',
        'brand_hint',
    ],
    'default_settings' => [
        'validation.warning_minutes' => 60,
        'validation.serious_minutes' => 180,
        'validation.alarming_minutes' => 360,
        'validation.critical_minutes' => 720,
        'validation.receiver_name_similarity' => 0.90,
        'validation.require_receiver_name' => true,
        'ai.enabled' => (bool) env('AI_ENABLED', false),
        'ai.agent_extraction_enabled' => true,
        'ai.bank_extraction_enabled' => true,
        'ai.quality_check_enabled' => true,
        'ai.brand_detection_enabled' => true,
        'ai.min_quality_score' => (float) env('AI_MIN_QUALITY_SCORE', 0.80),
        'ai.min_critical_confidence' => (float) env('AI_MIN_CRITICAL_CONFIDENCE', 0.75),
        'ai.auto_accept_confidence' => (float) env('AI_AUTO_ACCEPT_CONFIDENCE', 0.90),
        'check_et.enabled' => (bool) env('CHECK_ET_ENABLED', false),
        'check_et.outage_mode' => env('CHECK_ET_OUTAGE_MODE', 'review'),
        'check_et.failure_mode' => env('CHECK_ET_FAILURE_MODE', 'review'),
        'check_et.timeout_seconds' => (int) env('CHECK_ET_TIMEOUT_SECONDS', 8),
        'check_et.retries' => (int) env('CHECK_ET_RETRIES', 1),
        'credit.default_due_days' => 7,
        'credit.warning_overdue_days' => 1,
        'credit.serious_overdue_days' => 3,
        'credit.critical_overdue_days' => 7,
    ],
];
