<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Agent Audit') · {{ config('app.name') }}</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"></head><body>
<div class="app">
<aside class="sidebar"><div class="brandmark"><div class="branddot">A</div><span>Agent Audit</span></div>
<nav class="nav">
@if(auth()->user()->isAdmin())
<div class="nav-section">Overview</div><a class="{{ request()->routeIs('admin.dashboard')?'active':'' }}" href="{{ route('admin.dashboard') }}">⌂ <span>Dashboard</span></a><a class="{{ request()->routeIs('admin.transactions.*')?'active':'' }}" href="{{ route('admin.transactions.index') }}">⇄ <span>Transactions</span></a><a class="{{ request()->routeIs('admin.corrections.*')?'active':'' }}" href="{{ route('admin.corrections.index') }}">✓ <span>Approvals</span></a><a class="{{ request()->routeIs('admin.credits.*')?'active':'' }}" href="{{ route('admin.credits.index') }}">◉ <span>Credit</span></a><a class="{{ request()->routeIs('admin.commissions.*')?'active':'' }}" href="{{ route('admin.commissions.index') }}">◇ <span>Commission</span></a><a class="{{ request()->routeIs('admin.reports.*')?'active':'' }}" href="{{ route('admin.reports.index') }}">▥ <span>Reports</span></a>
<div class="nav-section admin-extra">Master data</div><a class="admin-extra {{ request()->routeIs('admin.brands.*')?'active':'' }}" href="{{ route('admin.brands.index') }}">◈ <span>Brands</span></a><a class="admin-extra {{ request()->routeIs('admin.agents.*')?'active':'' }}" href="{{ route('admin.agents.index') }}">◎ <span>Agents</span></a><a class="admin-extra {{ request()->routeIs('admin.agent-imports.*')?'active':'' }}" href="{{ route('admin.agent-imports.index') }}">⇧ <span>Agent Import</span></a><a class="admin-extra {{ request()->routeIs('admin.banks.*')?'active':'' }}" href="{{ route('admin.banks.index') }}">▣ <span>Banks</span></a><a class="admin-extra {{ request()->routeIs('admin.receiving-accounts.*')?'active':'' }}" href="{{ route('admin.receiving-accounts.index') }}">▤ <span>Receiving Accounts</span></a>
<div class="nav-section admin-extra">Administration</div><a class="admin-extra {{ request()->routeIs('admin.employees.*')?'active':'' }}" href="{{ route('admin.employees.index') }}">♙ <span>Users & Permissions</span></a><a class="admin-extra {{ request()->routeIs('admin.sessions.*')?'active':'' }}" href="{{ route('admin.sessions.index') }}">◉ <span>Device Sessions</span></a><a class="admin-extra {{ request()->routeIs('admin.audit.*')?'active':'' }}" href="{{ route('admin.audit.index') }}">≡ <span>Audit Log</span></a><a class="admin-extra {{ request()->routeIs('admin.settings.*')?'active':'' }}" href="{{ route('admin.settings.edit') }}">⚙ <span>Settings</span></a>
@else
<a class="{{ request()->routeIs('employee.home')?'active':'' }}" href="{{ route('employee.home') }}">⌂ <span>Home</span></a><a class="{{ request()->routeIs('employee.transactions.create')?'active':'' }}" href="{{ route('employee.transactions.create') }}">＋ <span>New</span></a><a class="{{ request()->routeIs('employee.transactions.index')||request()->routeIs('employee.transactions.show')?'active':'' }}" href="{{ route('employee.transactions.index') }}">≡ <span>History</span></a>
@endif
</nav></aside>
<main class="main"><header class="topbar"><h1>@yield('topbar','Agent Audit')</h1><div class="userbox"><div class="avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div><div class="mobile-hide"><a href="{{ route('profile.edit') }}" style="color:inherit;text-decoration:none"><b>{{ auth()->user()->name }}</b><div class="tiny muted">{{ ucfirst(auth()->user()->role->value) }} · Profile</div></a></div><form method="post" action="{{ route('logout') }}">@csrf<button class="btn btn-sm btn-outline">Logout</button></form></div></header><div class="content">
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error"><b>Please check:</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')</div></main></div></body></html>
